version: '3.7'
services:

  prometheus:
    image: prom/prometheus:v2.19.0
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
      - ./var/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - './var/mysql:/var/lib/mysql'
      - './ops/database:/docker-entrypoint-initdb.d'
      - './var/log/mysql:/var/log/mysql'

  mysqld_exporter:
    image: prom/mysqld-exporter
    user: root
    ports:
      - '9104:9104'
    links:
      - mysql
    environment:
      - "DATA_SOURCE_NAME=root:password@(mysql:3306)/db"
      - "collect.info_schema.tablestats=true"
      - "collect.info_schema.userstats=true"
      - "collect.info_schema.query_response_time=true"
      - "collect.auto_increment.columns=true"
      - "collect.perf_schema.tableiowaits=true"
      - "collect.perf_schema.tablelocks=true"
    depends_on:
      - mysql