global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codely-app'

rule_files:
  - "/etc/prometheus/alertmanager/rules.yml"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'codely'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081']

  - job_name: 'mysqld_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['mysqld_exporter:9104']